### ISSUE TITLE
Show exact date + number of days since today on Lost In Time questions

### ISSUE THREAD

**Issue by Aranir** [reminisceme/webapp#34]
Currently the lost in time questions are displayed with number of days since today.

Humans are generally very badly equipped to remember past events if they happened more than 5-7 ago if the number of days are given. They are more accustomed to remember dates in order of years and months therefore it would be better to display (maybe in addition to the number of days) the exact date they are choosing (in year, month, day).

This would make this question (which is already hard to answer) easier for the human mind.

**Comment by Aranir** [comment]
It now always resets to the default value. The date can't be selected anymore (probably due to some refresh?)

Could you look into it?

**Comment by romac** [comment]
Fixed, sorry for the inconvenience.
