### ISSUE TITLE
Friends search not working

### ISSUE THREAD

**Issue by Aranir** [reminisceme/webapp#35]
When I try to find other people to play against, no one ever gets found (it just displays searching).

**Comment by romac** [comment]
I'm unable to reproduce the issue as it appears to be working for me and Jeremy.

Can you take a look at what network requests are performed and also make sure that you've granted the app enough rights?

**Comment by Aranir** [comment]
Ok it appears to be working, but the other user didn't use his correct name.

It would be better of a more clear indication was given instead of "Searching..." if no one could be found with that search string no?

**Comment by romac** [comment]
Definitely. I'll open another issue.
