### ISSUE TITLE
Liked pages are not well aligned

### ISSUE THREAD

**Issue by Aranir** [reminisceme/webapp#37]
Due to the different image sizes, the liked pages button can get misaligned.
![screen shot 2015-01-23 at 14 27 15](https://cloud.githubusercontent.com/assets/1159256/5875311/13e89c90-a30c-11e4-93bb-363c4a6d23eb.png)

**Comment by romac** [comment]
What do you think is best here? Crop the images to always get a square of the right size or just constraint width/height to get a deformed square?

**Comment by Aranir** [comment]
I personally don't like cropping (as you won't see the whole picture) but a default size would probably be a good idea.

I tried to get the default images like on the facebook pages but up until now they don't want to give me the official profile picture of the page.

So probably constraints on the size but without deforming the image or cropping it would be optimal.

**Comment by romac** [comment]
Okay, let’s do that.

**Comment by Aranir** [comment]
Ok I finally figured out how to get the profile picture. Basically you need to treat pages like users:

    273256826116571/picture?type=large&redirect=false

where the id is just a page id.

Now this will require a little work on the crawler, as each page now requires two requests to be made, unless you want to handle it on the client side (to be certain we always get the latest picture url and don't store potentially outdated ones in the db).

so what do you think? It would be consistent with the fb_user_id and the profile pictures we get there.

Let me know what you prefer.

**Comment by romac** [comment]
I can do it on the client side, no worries.

Do you know if it is possible to get a square image, or will I have to handle that in CSS as mentioned above?

**Comment by Aranir** [comment]
As far as I could tell there are always square images. Haven't tested exhaustively but they are like the profile pictures of users, so I assume they will always have the same dimensions.

**Comment by romac** [comment]
Awesome. Thanks.

**Comment by romac** [comment]
@Aranir @JRappaz In order to implement that, I need the page ID, which is currently not stored in the MySQL database, so I couldn't just modify the serializer. Can you guys take a look at that and get back to me? I think we could store the page's ids in `frontend_multiplechoice.prop_fbid_X` like we do for the user's ids for questions of type `WhoLikedThisPost`, etc.) and then instead of storing + serializing the path to the page's image, we can just store and serialize its ID instead.

**Comment by Aranir** [comment]
I have an implementation where I give back the fb_page_id with the answers. I used the same implementation as we have for fb_users 

    {
    "text": "Volor Flex",
    "image_url": "https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-prn2/v/t1.0-9/p720x720/563805_380921075275688_336483152_n.jpg?oh=f54aaac8052fe4b692250773d01f47d5&oe=54DEC089&__gda__=1424019960_b7da046b845082412acc7a2327f4b3b5",
    "fb_id": "267860519915078"
}

@JRappaz would this implementation already work on your end? Let me know when I can deploy the adapted jar on the server.

**Comment by Aranir** [comment]
Ok game creator is updated on the server @JRappaz is working on the backend now.

@romac will you have time to update it until tuesday?

**Comment by romac** [comment]
No problem!

---

**Comment by Aranir** [comment]
Ok the updated jar is deployed. 

@romac could you adapt the client code to the newly returned ids in the value field of the possibilities?

To query for the page and get the profile picture?

**Comment by romac** [comment]
Closed in e2b08e65b584b5e7ac912f9e9b79725fcb5a1d0d.
