### ISSUE TITLE
Choices display only ... for facebook users

### ISSUE THREAD

**Issue by Aranir** [reminisceme/webapp#38]
Instead of showing the facebook user, sometimes it only displays "..." for the answer selection.

![10939069_10153551708638012_2144085253_o](https://cloud.githubusercontent.com/assets/1159256/5875333/43c2ed76-a30c-11e4-9e41-c9d4bf6c3ffa.jpg)

**Comment by romac** [comment]
Can you check the network requests that are performed? You should see one request per user to the Facebook API, that should return their public information (including their name, which I then display in the button).

**Comment by Aranir** [comment]
Could you give me a hint of how to do this? Using wireshark or are there simpler methods?

Also we noticed it happens for newly created users (I invited a few friends to test it out) and for each one of them it was the same.

**Comment by romac** [comment]
You can use Chrome's or Firefox's Web Inspector, and peek into the Network tab.

**Comment by Aranir** [comment]
Ok the get requests are done but errors are returned:

`Unsupported get request. Please read documentatin... type: GraphMethodException -> Code: 100`

The request looks like this: 

    https://graph.facebook.com/v2.1/10204595647545501?callback=FB.__globalCallbacks.f196cefc24&method=get&pretty=0&sdk=joey

**Comment by romac** [comment]
Okay, that's weird. I'll look into it. Looks like an issue with app-specific ids VS global ones.

Anyway, fetching users' names on the client feels a bit like a hack and introduce a noticeable delay. While I could perform those requests ahead of time and cache the results, I feel like it'd be cleaner to handle the client the names to display rather than just the ids. Then `choice.text` would be the name and `choice.value` would be the Facebook id. I'm not sure whether the crawler or the backend should take care of that (although the crawler seems like a more reasonable place to have that happening, as its job is specifically to fetch data from Facebook). What do you think?

**Comment by Aranir** [comment]
The Game-Creator already sends the username:

    {
    "text": "John Doe",
    "image_url": "",
    "fb_id": "10152798392786192"
   }


Therefore @JRappaz maybe needs to update the backend to send the correct values to you?

But for the Images for these users, will you handle it on the client side or should I handle it with the crawler?

**Comment by romac** [comment]
Yeah that should do it I guess :)

I can do it client-side by fetching the user’s avatar the same way I fetch avatars for pages (ie. `<img src="https://graph.facebook.com/USER_ID/avatar" />`, so there's nothing more to do on your side :)

I'll take care of it today.

**Comment by Aranir** [comment]
Ok great thank you.

Please let me know when its done, as I will ask some beta testers to play some games as soon as it works to gather some data.

**Comment by romac** [comment]
It's done, but it only displays IDs again as the backend doesn't return the names yet, as seen here:

```javascript
{
  title: "Who made this comment on the post?",
  propType: "fbid",
  choices: [
    {
      text: "10152541376332201",
      value: ""
    },
    {
      text: "10155115092420144",
      value: ""
    },
    {
      text: "1550704362",
      value: ""
    },
    {
      text: "10204326310491712",
      value: ""
    }
  ],
  post: {
    comment: "correct!",
    text: "Decaffeinated coffee is like long-distance relationships: pointless and frustrating.",
    type: "comment"
  },
  type: "MultipleChoice",
  id: 187
},
```

**Comment by Aranir** [comment]
It displays now the names with the avatars, but sometimes the avatars don't corresponds to the names.

Could it be due to the global and app specific IDs?

**Comment by romac** [comment]
It might be but I have no idea how to resolve that issue, especially since everything works fine here; every single picture I have been shown matches the given user name.

So I'm not sure what to do?

**Comment by Aranir** [comment]
Do you request the avatars with the app specific access token?

**Comment by romac** [comment]
I'll try doing that.

**Comment by romac** [comment]
Okay done in 37f48a0 and pushed to `dev`. Tell me if that fixes things for you.
