### ISSUE TITLE
Polling strategy not optimal

### ISSUE THREAD

**Issue by Aranir** [reminisceme/webapp#39]
After completing a turn the UI does not always update correct (still showing its my turn) and the answered tile stays unanswered.

This is probably due to the polling strategy?

The UI should be more responsive in this regard

**Comment by romac** [comment]
That could also be a bug with the backend. Can you make sure that the information returned by the backend API (at `/api/games/GAMEID`) is correct? (ie. if it's not your turn, there should be no "token", etc.) If it is, then yeah that's probably a bug in the client code.

**Comment by Aranir** [comment]
But even if it the token would be falsely returned, the tile should in any case show the new state of the board no?

Or is the token also necessary to update the tile state?

**Comment by romac** [comment]
Indeed. No the token isn’t needed to do that.  

Can you make sure that the API returns what you expect it to return?

In the mean time, I’ll look into triggering a refresh of the game board when we’re done answering a tile’s questions, to speed up the refresh.

**Comment by Aranir** [comment]
I think its best if @JRappaz looks into this as he can probably better judge what needs to be there than me...

**Comment by Aranir** [comment]
Is there any update on this? As the game boards does not correctly updated after conquering the tiles.

Can you update this until tomorrow?

**Comment by romac** [comment]
Again, I'm not seeing any issue on my side. The tiles update themselves right after I click the "Close" button, points get updated and the turns switch as expected. As I am unable to reproduce that issue, I'm gonna need you to investigate this further, perhaps by checking what the API returns at `/api/games/GAME_ID/` etc.
