### ISSUE TITLE
Remove finished games

### ISSUE THREAD

**Issue by Aranir** [reminisceme/webapp#41]
On the left panel we show the current games, but even completed games are shown. 

We should remove the completed games under the current games panel.

**Comment by romac** [comment]
I can filter them out easily, but shouldn't that be handled by the backend? Anyway, it's a quick fix that I can perfectly apply if @JRappaz is busy with something else.

**Comment by JRappaz** [comment]
I can handle this :) in a moment... Note to myself: Games shouldn't be in the list when join request not already accepted

**Comment by romac** [comment]
Agreed. We should maybe show them in the Join Requests lists, with a PENDING label or something, so that people can keep track of what requests they've sent (and possibly cancel them).

**Comment by romac** [comment]
Moved to reminisceme/backend#49.
